### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by Nick3380** [DAQEM/TinyMobFarmRemastered#16]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-10-06 15:55:45
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tinymobfarm' at 'com.daqem.tinymobfarm.fabric.TinyMobFarmCommonFabric'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_1792$class_1793 net.minecraft.class_1792$class_1793.method_7898(int)'
	at com.daqem.tinymobfarm.item.LassoItem.<init>(LassoItem.java:35)
	at com.daqem.tinymobfarm.TinyMobFarm.lambda$static$13(TinyMobFarm.java:63)
	at dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232)
	at com.daqem.tinymobfarm.TinyMobFarm.<clinit>(TinyMobFarm.java:63)
	at com.daqem.tinymobfarm.fabric.TinyMobFarmCommonFabric.onInitialize(TinyMobFarmCommonFabric.java:10)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more

**Comment by DAQEM** [comment]
What MC version are you using?
